.POSIX:
PROJECTDIR =../../..
include $(PROJECTDIR)/scripts/rules.mk
include ../rules.mk

OBJS = abort.o\
       abs.o\
       atexit.o\
       atoi.o\
       atol.o\
       atoll.o\
       bsearch.o\
       calloc.o\
       errno.o\
       exit.o\
       labs.o\
       llabs.o\
       malloc.o\
       qsort.o\
       rand.o\
       realloc.o\
       strtoul.o\
       strtoull.o\

all: $(OBJS)
