.TH strlen 3
.SH NAME
strlen - get the length of a string
.SH SYNOPSIS
#include <string.h>

size_t strlen(const char *s)
.SH DESCRIPTION
The
.BR strlen ()
function computes the length of the string
pointed to by
.I s
.SH RETURN VALUE
The function shall return the length of the string
.IR s .
.SH STANDARDS
ISO/IEC 9899:1999 Section 7.21.6.3
