.TH strpbrk 3
.SH NAME
strpbrk - scan a string for a byte
.SH SYNOPSIS
#include <string.h>

char *strpbrk(const char *s1, const char *s2)
.SH DESCRIPTION
The
.BR strpbrk ()
function locates the first occurence
in the string pointed to by
.I s1
of any character from
the string pointed to by
.IR s2 .
.SH RETURN VALUE
The
.BR strpbrk ()
function shall return a pointer to the character in
.I s1
or a null pointer if
.I s2
does not occur in
.IR s1 .
.SH STANDARDS
ISO/IEC 9899:1999 Section 7.21.5.4
