parser.c: $(PROJECTDIR)/inc/$(STD)/cstd.h
target/amd64-sysv/code.o: $(INCDIR)/$(STD)/cstd.h
target/i386-sysv/code.o: $(INCDIR)/$(STD)/cstd.h
target/qbe/cgen.o: $(INCDIR)/$(STD)/cstd.h
target/z80-scc/code.o: $(INCDIR)/$(STD)/cstd.h

#deps
code.o: ../inc/scc.h
code.o: cc2.h
main.o: ../inc/arg.h
main.o: ../inc/scc.h
main.o: cc2.h
main.o: error.h
node.o: ../inc/scc.h
node.o: cc2.h
optm.o: ../inc/scc.h
optm.o: cc2.h
parser.o: ../inc/scc.h
parser.o: cc2.h
peep.o: ../inc/scc.h
peep.o: cc2.h
symbol.o: ../inc/scc.h
symbol.o: cc2.h
target/amd64-sysv/cgen.o: target/amd64-sysv/../../../inc/scc.h
target/amd64-sysv/cgen.o: target/amd64-sysv/../../cc2.h
target/amd64-sysv/cgen.o: target/amd64-sysv/arch.h
target/amd64-sysv/code.o: target/amd64-sysv/../../../inc/scc.h
target/amd64-sysv/code.o: target/amd64-sysv/../../cc2.h
target/amd64-sysv/code.o: target/amd64-sysv/arch.h
target/amd64-sysv/optm.o: target/amd64-sysv/../../../inc/scc.h
target/amd64-sysv/optm.o: target/amd64-sysv/../../cc2.h
target/amd64-sysv/types.o: target/amd64-sysv/../../../inc/scc.h
target/amd64-sysv/types.o: target/amd64-sysv/../../cc2.h
target/i386-sysv/cgen.o: target/i386-sysv/../../../inc/scc.h
target/i386-sysv/cgen.o: target/i386-sysv/../../cc2.h
target/i386-sysv/cgen.o: target/i386-sysv/arch.h
target/i386-sysv/code.o: target/i386-sysv/../../../inc/scc.h
target/i386-sysv/code.o: target/i386-sysv/../../cc2.h
target/i386-sysv/code.o: target/i386-sysv/arch.h
target/i386-sysv/optm.o: target/i386-sysv/../../../inc/scc.h
target/i386-sysv/optm.o: target/i386-sysv/../../cc2.h
target/i386-sysv/types.o: target/i386-sysv/../../../inc/scc.h
target/i386-sysv/types.o: target/i386-sysv/../../cc2.h
target/qbe/cgen.o: target/qbe/../../../inc/scc.h
target/qbe/cgen.o: target/qbe/../../cc2.h
target/qbe/cgen.o: target/qbe/arch.h
target/qbe/code.o: target/qbe/../../../inc/scc.h
target/qbe/code.o: target/qbe/../../cc2.h
target/qbe/code.o: target/qbe/arch.h
target/qbe/optm.o: target/qbe/../../../inc/scc.h
target/qbe/optm.o: target/qbe/../../cc2.h
target/z80-scc/cgen.o: target/z80-scc/../../../inc/scc.h
target/z80-scc/cgen.o: target/z80-scc/../../cc2.h
target/z80-scc/cgen.o: target/z80-scc/arch.h
target/z80-scc/code.o: target/z80-scc/../../../inc/scc.h
target/z80-scc/code.o: target/z80-scc/../../cc2.h
target/z80-scc/code.o: target/z80-scc/arch.h
target/z80-scc/optm.o: target/z80-scc/../../../inc/scc.h
target/z80-scc/optm.o: target/z80-scc/../../cc2.h
target/z80-scc/types.o: target/z80-scc/../../../inc/scc.h
target/z80-scc/types.o: target/z80-scc/../../cc2.h
