alloc.o: ../../inc/scc.h
bpack.o: ../../inc/scc.h
bunpack.o: ../../inc/scc.h
casecmp.o: ../../inc/scc.h
debug.o: ../../inc/scc.h
die.o: ../../inc/scc.h
lpack.o: ../../inc/scc.h
lunpack.o: ../../inc/scc.h
newitem.o: ../../inc/scc.h
rmyro.o: ../../inc/myro.h
rmyro.o: ../../inc/scc.h
wmyro.o: ../../inc/myro.h
wmyro.o: ../../inc/scc.h
xcalloc.o: ../../inc/scc.h
xmalloc.o: ../../inc/scc.h
xrealloc.o: ../../inc/scc.h
xstrdup.o: ../../inc/scc.h
