#deps
./coff32del.o: $(INCDIR)/scc/scc/mach.h
./coff32del.o: ./../libmach.h
./coff32del.o: ./coff32.h
./coff32getidx.o: $(INCDIR)/scc/scc/cstd.h
./coff32getidx.o: $(INCDIR)/scc/scc/mach.h
./coff32getidx.o: ./../libmach.h
./coff32getidx.o: ./coff32.h
./coff32getindex.o: $(INCDIR)/scc/scc/mach.h
./coff32getindex.o: ./../libmach.h
./coff32getindex.o: ./coff32.h
./coff32getsect.o: $(INCDIR)/scc/scc/mach.h
./coff32getsect.o: ./../libmach.h
./coff32getsect.o: ./coff32.h
./coff32namidx.o: $(INCDIR)/scc/scc/mach.h
./coff32new.o: $(INCDIR)/scc/scc/mach.h
./coff32new.o: ./../libmach.h
./coff32new.o: ./coff32.h
./coff32probe.o: $(INCDIR)/scc/scc/mach.h
./coff32probe.o: ./../libmach.h
./coff32probe.o: ./coff32.h
./coff32read.o: $(INCDIR)/scc/scc/mach.h
./coff32read.o: ./../libmach.h
./coff32read.o: ./coff32.h
./coff32setidx.o: $(INCDIR)/scc/scc/mach.h
./coff32setidx.o: ./../libmach.h
./coff32setindex.o: $(INCDIR)/scc/scc/mach.h
./coff32setindex.o: ./../libmach.h
./coff32setindex.o: ./coff32.h
./coff32strip.o: $(INCDIR)/scc/scc/mach.h
./coff32strip.o: ./../libmach.h
./coff32strip.o: ./coff32.h
./coff32write.o: $(INCDIR)/scc/scc/mach.h
./coff32write.o: ./../libmach.h
./coff32write.o: ./coff32.h
