#deps
./coff32.o: $(INCDIR)/scc/scc/mach.h
./coff32.o: ./../libmach.h
./coff32.o: ./coff32.h
./coff32del.o: $(INCDIR)/scc/scc/mach.h
./coff32del.o: ./../libmach.h
./coff32del.o: ./coff32.h
./coff32getidx.o: $(INCDIR)/scc/scc/mach.h
./coff32getidx.o: ./../libmach.h
./coff32getidx.o: ./coff32.h
./coff32new.o: $(INCDIR)/scc/scc/mach.h
./coff32new.o: ./../libmach.h
./coff32new.o: ./coff32.h
./coff32probe.o: $(INCDIR)/scc/scc/mach.h
./coff32probe.o: ./../libmach.h
./coff32probe.o: ./coff32.h
./coff32read.o: $(INCDIR)/scc/scc/mach.h
./coff32read.o: ./../libmach.h
./coff32read.o: ./coff32.h
./coff32setidx.o: $(INCDIR)/scc/scc/mach.h
./coff32setidx.o: ./../libmach.h
./coff32setidx.o: ./coff32.h
./coff32strip.o: $(INCDIR)/scc/scc/mach.h
./coff32strip.o: ./../libmach.h
./coff32strip.o: ./coff32.h
./coff32sync.o: $(INCDIR)/scc/scc/mach.h
./coff32sync.o: ./../libmach.h
./coff32write.o: $(INCDIR)/scc/scc/mach.h
./coff32write.o: ./../libmach.h
./coff32write.o: ./coff32.h
./coff32xgetidx.o: $(INCDIR)/scc/scc/cstd.h
./coff32xgetidx.o: $(INCDIR)/scc/scc/mach.h
./coff32xgetidx.o: ./../libmach.h
./coff32xgetidx.o: ./coff32.h
./coff32xsetidx.o: $(INCDIR)/scc/scc/mach.h
./coff32xsetidx.o: ./../libmach.h
