#deps
coff32del.o: $(INCDIR)/scc/scc/mach.h
coff32del.o: ../libmach.h
coff32del.o: coff32.h
coff32index.o: $(INCDIR)/scc/scc/mach.h
coff32index.o: ../libmach.h
coff32index.o: coff32.h
coff32new.o: $(INCDIR)/scc/scc/mach.h
coff32new.o: ../libmach.h
coff32new.o: coff32.h
coff32probe.o: $(INCDIR)/scc/scc/mach.h
coff32probe.o: ../libmach.h
coff32probe.o: coff32.h
coff32read.o: $(INCDIR)/scc/scc/mach.h
coff32read.o: ../libmach.h
coff32read.o: coff32.h
coff32strip.o: $(INCDIR)/scc/scc/mach.h
coff32strip.o: ../libmach.h
coff32strip.o: coff32.h
coff32write.o: $(INCDIR)/scc/scc/mach.h
coff32write.o: ../libmach.h
coff32write.o: coff32.h
