.POSIX:
PROJECTDIR =../../..
include $(PROJECTDIR)/scripts/rules.mk

OBJS = coff32del.o \
       coff32index.o \
       coff32new.o \
       coff32probe.o \
       coff32read.o \
       coff32strip.o \
       coff32write.o \

all: $(OBJS)
