.POSIX:
PROJECTDIR =../../..
include $(PROJECTDIR)/scripts/rules.mk

OBJS = coff32del.o \
       coff32new.o \
       coff32probe.o \
       coff32read.o \
       coff32strip.o \
       coff32write.o \
       coff32setindex.o \
       coff32getindex.o \
       coff32setidx.o \
       coff32getidx.o \

all: $(OBJS)

dep: inc-dep

include deps.mk
