.POSIX:
PROJECTDIR =../../..
include $(PROJECTDIR)/scripts/rules.mk

MORECFLAGS = -w

OBJS = _daysyear.o\
       asctime.o\
       ctime.o\
       difftime.o\
       gmtime.o\
       localtime.o\
       mktime.o\
       strftime.o\

all: $(OBJS)
