.POSIX:
PROJECTDIR =../..
include $(PROJECTDIR)/scripts/rules.mk
include rules.mk
include objlst.mk

LIBC   = $(LIBCDIR)/libc.a
CRT    = $(LIBCDIR)/crt.o
TARGET = $(LIBC) $(CRT)

all: $(TARGET)

$(LIBC): $(OBJS)
	mklib -o $@ $?

$(CRT): arch/$(ARCH)/$(SYS)/crt.o
	cp arch/$(ARCH)/$(SYS)/crt.o $@
