extern int _brk(void *);
extern void _exit(int);
extern int _close(int);
extern int _getpid(void);
extern int _kill(int, int);
extern int _open(const char *, int, int);
extern int _read(int, void *, size_t);
extern int _unlink(const char *);
extern int _write(int, void *, size_t);
extern int _access(const char *, int);
extern long _lseek(int, long, int);
