COMMON_OBJS =\
	assert/__assert.$O\
	assert/assert.$O\
	ctype/ctype.$O\
	ctype/isalnum.$O\
	ctype/isalpha.$O\
	ctype/isascii.$O\
	ctype/isblank.$O\
	ctype/iscntrl.$O\
	ctype/isdigit.$O\
	ctype/isgraph.$O\
	ctype/islower.$O\
	ctype/isprint.$O\
	ctype/ispunct.$O\
	ctype/isspace.$O\
	ctype/isupper.$O\
	ctype/isxdigit.$O\
	ctype/toascii.$O\
	ctype/tolower.$O\
	ctype/toupper.$O\
	locale/localeconv.$O\
	locale/setlocale.$O\
	stdio/__getc.$O\
	stdio/__iob.$O\
	stdio/__putc.$O\
	stdio/_allocbuf.$O\
	stdio/_flsbuf.$O\
	stdio/_fpopen.$O\
	stdio/clearerr.$O\
	stdio/fclose.$O\
	stdio/feof.$O\
	stdio/ferror.$O\
	stdio/fflush.$O\
	stdio/fgetc.$O\
	stdio/fgets.$O\
	stdio/fopen.$O\
	stdio/fprintf.$O\
	stdio/fputc.$O\
	stdio/fputs.$O\
	stdio/fread.$O\
	stdio/freopen.$O\
	stdio/fseek.$O\
	stdio/ftell.$O\
	stdio/fwrite.$O\
	stdio/getc.$O\
	stdio/getchar.$O\
	stdio/gets.$O\
	stdio/perror.$O\
	stdio/printf.$O\
	stdio/putc.$O\
	stdio/putchar.$O\
	stdio/puts.$O\
	stdio/remove.$O\
	stdio/rename.$O\
	stdio/rewind.$O\
	stdio/setbuf.$O\
	stdio/setvbuf.$O\
	stdio/snprintf.$O\
	stdio/sprintf.$O\
	stdio/tmpnam.$O\
	stdio/ungetc.$O\
	stdio/vfprintf.$O\
	stdio/vprintf.$O\
	stdio/vsnprintf.$O\
	stdio/vsprintf.$O\
	stdlib/_Exit.$O\
	stdlib/_dtoi.$O\
	stdlib/abort.$O\
	stdlib/abs.$O\
	stdlib/atexit.$O\
	stdlib/atoi.$O\
	stdlib/atol.$O\
	stdlib/atoll.$O\
	stdlib/bsearch.$O\
	stdlib/calloc.$O\
	stdlib/div.$O\
	stdlib/errno.$O\
	stdlib/exit.$O\
	stdlib/labs.$O\
	stdlib/llabs.$O\
	stdlib/ldiv.$O\
	stdlib/lldiv.$O\
	stdlib/malloc.$O\
	stdlib/mblen.$O\
	stdlib/mbtowc.$O\
	stdlib/mbstowcs.$O\
	stdlib/qsort.$O\
	stdlib/rand.$O\
	stdlib/realloc.$O\
	stdlib/strtol.$O\
	stdlib/strtoll.$O\
	stdlib/strtoul.$O\
	stdlib/strtoull.$O\
	stdlib/wctomb.$O\
	string/strcat.$O\
	string/strchr.$O\
	string/strcmp.$O\
	string/strcoll.$O\
	string/strcpy.$O\
	string/strcspn.$O\
	string/strerror.$O\
	string/strncat.$O\
	string/strncmp.$O\
	string/strncpy.$O\
	string/strpbrk.$O\
	string/strrchr.$O\
	string/strspn.$O\
	string/strstr.$O\
	string/strtok.$O\
	string/strxfrm.$O\
	time/_daysyear.$O\
	time/_newyear.$O\
	time/asctime.$O\
	time/ctime.$O\
	time/difftime.$O\
	time/gmtime.$O\
	time/localtime.$O\
	time/mktime.$O\
	time/strftime.$O\
	time/tz.$O\
	wchar/mbrlen.$O\
	wchar/mbrtowc.$O\
	wchar/mbsrtowcs.$O\
	wchar/wcrtomb.$O\
	wchar/wcslen.$O\
	wchar/wcwidth.$O\
	wchar/_validutf8.$O\
