#deps
./addr2line.o: $(INCDIR)/scc/scc/mach.h
./archive.o: $(INCDIR)/scc/scc/ar.h
./archive.o: $(INCDIR)/scc/scc/mach.h
./archive.o: .libmach.h
./arindex.o: $(INCDIR)/scc/scc/mach.h
./arindex.o: .libmach.h
./armember.o: $(INCDIR)/scc/scc/ar.h
./armember.o: $(INCDIR)/scc/scc/mach.h
./artraverse.o: $(INCDIR)/scc/scc/ar.h
./artraverse.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32del.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32del.o: ./coff32../libmach.h
./coff32/coff32del.o: ./coff32coff32.h
./coff32/coff32index.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32index.o: ./coff32../libmach.h
./coff32/coff32index.o: ./coff32coff32.h
./coff32/coff32new.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32new.o: ./coff32../libmach.h
./coff32/coff32new.o: ./coff32coff32.h
./coff32/coff32probe.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32probe.o: ./coff32../libmach.h
./coff32/coff32probe.o: ./coff32coff32.h
./coff32/coff32read.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32read.o: ./coff32../libmach.h
./coff32/coff32read.o: ./coff32coff32.h
./coff32/coff32strip.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32strip.o: ./coff32../libmach.h
./coff32/coff32strip.o: ./coff32coff32.h
./coff32/coff32write.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32write.o: ./coff32../libmach.h
./coff32/coff32write.o: ./coff32coff32.h
./coffelf32.o: $(INCDIR)/scc/scc/mach.h
./coffelf32.o: .libmach.h
./del.o: $(INCDIR)/scc/scc/mach.h
./del.o: .libmach.h
./foridx.o: $(INCDIR)/scc/scc/mach.h
./foridx.o: .libmach.h
./forsect.o: $(INCDIR)/scc/scc/mach.h
./forsect.o: .libmach.h
./forsym.o: $(INCDIR)/scc/scc/mach.h
./forsym.o: .libmach.h
./index.o: $(INCDIR)/scc/scc/mach.h
./index.o: .libmach.h
./new.o: $(INCDIR)/scc/scc/mach.h
./new.o: .libmach.h
./objdel.o: $(INCDIR)/scc/scc/mach.h
./objdel.o: .libmach.h
./objfree.o: $(INCDIR)/scc/scc/mach.h
./objfree.o: .libmach.h
./objlookup.o: $(INCDIR)/scc/scc/mach.h
./objnew.o: $(INCDIR)/scc/scc/mach.h
./objnew.o: .libmach.h
./objpos.o: $(INCDIR)/scc/scc/mach.h
./objpos.o: .libmach.h
./objread.o: $(INCDIR)/scc/scc/mach.h
./objread.o: .libmach.h
./objreset.o: $(INCDIR)/scc/scc/mach.h
./objreset.o: .libmach.h
./objstrip.o: $(INCDIR)/scc/scc/mach.h
./objstrip.o: .libmach.h
./objtype.o: $(INCDIR)/scc/scc/mach.h
./objtype.o: .libmach.h
./objwrite.o: $(INCDIR)/scc/scc/mach.h
./objwrite.o: .libmach.h
./pack.o: $(INCDIR)/scc/scc/mach.h
./pack.o: .libmach.h
./probe.o: $(INCDIR)/scc/scc/mach.h
./probe.o: .libmach.h
./read.o: $(INCDIR)/scc/scc/mach.h
./read.o: .libmach.h
./strip.o: $(INCDIR)/scc/scc/mach.h
./strip.o: .libmach.h
./unpack.o: $(INCDIR)/scc/scc/mach.h
./unpack.o: .libmach.h
./write.o: $(INCDIR)/scc/scc/mach.h
./write.o: .libmach.h
