#deps
./addr2line.o: $(INCDIR)/scc/scc/mach.h
./archive.o: $(INCDIR)/scc/scc/ar.h
./archive.o: $(INCDIR)/scc/scc/mach.h
./archive.o: ./libmach.h
./armember.o: $(INCDIR)/scc/scc/ar.h
./armember.o: $(INCDIR)/scc/scc/mach.h
./formember.o: $(INCDIR)/scc/scc/ar.h
./formember.o: $(INCDIR)/scc/scc/mach.h
./getindex.o: $(INCDIR)/scc/scc/mach.h
./getindex.o: ./libmach.h
./objaddseg.o: $(INCDIR)/scc/scc/mach.h
./objdel.o: $(INCDIR)/scc/scc/mach.h
./objdel.o: ./libmach.h
./objfree.o: $(INCDIR)/scc/scc/mach.h
./objfree.o: ./libmach.h
./objlookup.o: $(INCDIR)/scc/scc/mach.h
./objlookup.o: $(INCDIR)/scc/scc/scc.h
./objnew.o: $(INCDIR)/scc/scc/mach.h
./objnew.o: ./libmach.h
./objpos.o: $(INCDIR)/scc/scc/mach.h
./objpos.o: ./libmach.h
./objread.o: $(INCDIR)/scc/scc/mach.h
./objread.o: ./libmach.h
./objstrip.o: $(INCDIR)/scc/scc/mach.h
./objstrip.o: ./libmach.h
./objsync.o: $(INCDIR)/scc/scc/mach.h
./objsync.o: ./libmach.h
./objtype.o: $(INCDIR)/scc/scc/mach.h
./objtype.o: ./libmach.h
./objwrite.o: $(INCDIR)/scc/scc/mach.h
./objwrite.o: ./libmach.h
./pack.o: $(INCDIR)/scc/scc/mach.h
./pack.o: ./libmach.h
./setindex.o: $(INCDIR)/scc/scc/mach.h
./setindex.o: ./libmach.h
./unpack.o: $(INCDIR)/scc/scc/mach.h
./unpack.o: ./libmach.h
