#deps
./addr2line.o: $(INCDIR)/scc/scc/mach.h
./archive.o: $(INCDIR)/scc/scc/ar.h
./archive.o: $(INCDIR)/scc/scc/mach.h
./archive.o: ./libmach.h
./armember.o: $(INCDIR)/scc/scc/ar.h
./armember.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32del.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32del.o: ./coff32/../libmach.h
./coff32/coff32del.o: ./coff32/coff32.h
./coff32/coff32getidx.o: $(INCDIR)/scc/scc/cstd.h
./coff32/coff32getidx.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32getidx.o: ./coff32/../libmach.h
./coff32/coff32getidx.o: ./coff32/coff32.h
./coff32/coff32getindex.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32getindex.o: ./coff32/../libmach.h
./coff32/coff32getindex.o: ./coff32/coff32.h
./coff32/coff32getsect.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32getsect.o: ./coff32/../libmach.h
./coff32/coff32getsect.o: ./coff32/coff32.h
./coff32/coff32namidx.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32new.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32new.o: ./coff32/../libmach.h
./coff32/coff32new.o: ./coff32/coff32.h
./coff32/coff32probe.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32probe.o: ./coff32/../libmach.h
./coff32/coff32probe.o: ./coff32/coff32.h
./coff32/coff32read.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32read.o: ./coff32/../libmach.h
./coff32/coff32read.o: ./coff32/coff32.h
./coff32/coff32setidx.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32setidx.o: ./coff32/../libmach.h
./coff32/coff32setindex.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32setindex.o: ./coff32/../libmach.h
./coff32/coff32setindex.o: ./coff32/coff32.h
./coff32/coff32strip.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32strip.o: ./coff32/../libmach.h
./coff32/coff32strip.o: ./coff32/coff32.h
./coff32/coff32write.o: $(INCDIR)/scc/scc/mach.h
./coff32/coff32write.o: ./coff32/../libmach.h
./coff32/coff32write.o: ./coff32/coff32.h
./del.o: $(INCDIR)/scc/scc/mach.h
./del.o: ./libmach.h
./formember.o: $(INCDIR)/scc/scc/ar.h
./formember.o: $(INCDIR)/scc/scc/mach.h
./forsym.o: $(INCDIR)/scc/scc/mach.h
./forsym.o: ./libmach.h
./getidx.o: $(INCDIR)/scc/scc/mach.h
./getidx.o: ./libmach.h
./getindex.o: $(INCDIR)/scc/scc/mach.h
./getindex.o: ./libmach.h
./getsect.o: $(INCDIR)/scc/scc/mach.h
./getsect.o: ./libmach.h
./namidx.o: $(INCDIR)/scc/scc/mach.h
./namidx.o: ./libmach.h
./namindex.o: $(INCDIR)/scc/scc/mach.h
./namindex.o: ./libmach.h
./new.o: $(INCDIR)/scc/scc/mach.h
./new.o: ./libmach.h
./objdel.o: $(INCDIR)/scc/scc/mach.h
./objdel.o: ./libmach.h
./objfree.o: $(INCDIR)/scc/scc/mach.h
./objfree.o: ./libmach.h
./objlookup.o: $(INCDIR)/scc/scc/mach.h
./objlookup.o: $(INCDIR)/scc/scc/scc.h
./objnew.o: $(INCDIR)/scc/scc/mach.h
./objnew.o: ./libmach.h
./objpos.o: $(INCDIR)/scc/scc/mach.h
./objpos.o: ./libmach.h
./objread.o: $(INCDIR)/scc/scc/mach.h
./objread.o: ./libmach.h
./objsect.o: $(INCDIR)/scc/scc/mach.h
./objsect.o: ./libmach.h
./objstrip.o: $(INCDIR)/scc/scc/mach.h
./objstrip.o: ./libmach.h
./objtype.o: $(INCDIR)/scc/scc/mach.h
./objtype.o: ./libmach.h
./objwrite.o: $(INCDIR)/scc/scc/mach.h
./objwrite.o: ./libmach.h
./pack.o: $(INCDIR)/scc/scc/mach.h
./pack.o: ./libmach.h
./probe.o: $(INCDIR)/scc/scc/mach.h
./probe.o: ./libmach.h
./read.o: $(INCDIR)/scc/scc/mach.h
./read.o: ./libmach.h
./setidx.o: $(INCDIR)/scc/scc/mach.h
./setidx.o: ./libmach.h
./setindex.o: $(INCDIR)/scc/scc/mach.h
./setindex.o: ./libmach.h
./strip.o: $(INCDIR)/scc/scc/mach.h
./strip.o: ./libmach.h
./unpack.o: $(INCDIR)/scc/scc/mach.h
./unpack.o: ./libmach.h
./write.o: $(INCDIR)/scc/scc/mach.h
./write.o: ./libmach.h
