.POSIX:
PROJECTDIR =../..
include $(PROJECTDIR)/scripts/rules.mk
include objlst.mk

TARGET = $(LIBDIR)/scc/libmach.a

all: $(TARGET)

$(TARGET): $(OBJS)
	$(AR) $(PROJ_ARFLAGS) $@ $?
	$(RL) $(PROJ_RLFLAGS) $@
