#!/bin/sh

for i
do
	case "$1" in
	-t)
		target=$2
		shift 2
		;;
	-o)
		out=$2
		shift 2
		;;
	-*)
		echo mktbl [-t target][-o file] >&2
		exit 1
		;;
	*)
		break
		;;
	esac
done

cat < formats.lst > $out <<EOF
#include <stdio.h>
#include <scc/mach.h>
#include "libmach.h"

${target}fun_t ${target}v[] = {
`while read i
 do
	printf "\t%s," ${i}${target}
 done`
};
EOF
