#deps
amd64-sysv.o: $(INCDIR)/bits/scc/scc.h
amd64-sysv.o: cc1.h
arch.o: $(INCDIR)/bits/scc/scc.h
arch.o: cc1.h
arm64-sysv.o: $(INCDIR)/bits/scc/scc.h
arm64-sysv.o: cc1.h
builtin.o: $(INCDIR)/bits/scc/scc.h
builtin.o: cc1.h
code.o: $(INCDIR)/bits/scc/scc.h
code.o: cc1.h
cpp.o: $(INCDIR)/bits/scc/cstd.h
cpp.o: $(INCDIR)/bits/scc/scc.h
cpp.o: cc1.h
decl.o: $(INCDIR)/bits/scc/cstd.h
decl.o: $(INCDIR)/bits/scc/scc.h
decl.o: cc1.h
error.o: $(INCDIR)/bits/scc/scc.h
error.o: cc1.h
expr.o: $(INCDIR)/bits/scc/cstd.h
expr.o: $(INCDIR)/bits/scc/scc.h
expr.o: cc1.h
fold.o: $(INCDIR)/bits/scc/scc.h
fold.o: cc1.h
i386-sysv.o: $(INCDIR)/bits/scc/scc.h
i386-sysv.o: cc1.h
init.o: $(INCDIR)/bits/scc/cstd.h
init.o: $(INCDIR)/bits/scc/scc.h
init.o: cc1.h
lex.o: $(INCDIR)/bits/scc/cstd.h
lex.o: $(INCDIR)/bits/scc/scc.h
lex.o: cc1.h
main.o: $(INCDIR)/bits/scc/arg.h
main.o: $(INCDIR)/bits/scc/scc.h
main.o: cc1.h
stmt.o: $(INCDIR)/bits/scc/cstd.h
stmt.o: $(INCDIR)/bits/scc/scc.h
stmt.o: cc1.h
symbol.o: $(INCDIR)/bits/scc/cstd.h
symbol.o: $(INCDIR)/bits/scc/scc.h
symbol.o: cc1.h
types.o: $(INCDIR)/bits/scc/cstd.h
types.o: $(INCDIR)/bits/scc/scc.h
types.o: cc1.h
z80-scc.o: $(INCDIR)/bits/scc/scc.h
z80-scc.o: cc1.h
