#deps
expr.o: $(INCDIR)/scc/scc/scc.h
expr.o: as.h
ins.o: $(INCDIR)/scc/scc/scc.h
ins.o: as.h
main.o: $(INCDIR)/scc/scc/arg.h
main.o: $(INCDIR)/scc/scc/scc.h
main.o: as.h
parser.o: $(INCDIR)/scc/scc/cstd.h
parser.o: $(INCDIR)/scc/scc/scc.h
parser.o: as.h
symbol.o: $(INCDIR)/scc/scc/scc.h
symbol.o: as.h
target/x80/ins.o: $(INCDIR)/scc/scc/scc.h
target/x80/ins.o: target/x80/../../as.h
target/x80/ins.o: target/x80/proc.h
target/x80/z80.o: $(INCDIR)/scc/scc/scc.h
target/x80/z80.o: target/x80/../../as.h
target/x80/z80.o: target/x80/../x80/proc.h
target/x86/amd64.o: $(INCDIR)/scc/scc/scc.h
target/x86/amd64.o: target/x86/../../as.h
target/x86/i286.o: $(INCDIR)/scc/scc/scc.h
target/x86/i286.o: target/x86/../../as.h
target/x86/i286.o: target/x86/../x86/proc.h
target/x86/i386.o: $(INCDIR)/scc/scc/scc.h
target/x86/i386.o: target/x86/../../as.h
target/x86/i386.o: target/x86/../x86/proc.h
target/x86/ins.o: $(INCDIR)/scc/scc/scc.h
target/x86/ins.o: target/x86/../../as.h
target/x86/ins.o: target/x86/proc.h
