#!/bin/sh

case `uname` in
OpenBSD)
	echo TOOL=${TOOL:-clang} HOST=bsd ARFLAGS=${ARFLAGS:--rv}
	;;
NetBSD)
	#TODO: send a patch to NetBSD to solve this problem
	echo HOST=bsd ARFLAGS=${ARFLAGS:--rv}
	;;
*BSD)
	echo HOST=bsd
	;;
Linux)
	echo TOOL=${TOOL:-gnu} HOST=linux
	;;
Plan9)
	echo HOST=plan9
	;;
esac
