#!/bin/sh

case `uname` in
OpenBSD)
	echo TOOL=${TOOL:-clang} HOST=bsd ARFLAGS="${ARFLAGS:--rv}" NOPIE_LDFLAGS=-no-pie
	;;
NetBSD)
	#TODO: send a patch to NetBSD to solve this problem
	echo HOST=bsd ARFLAGS="${ARFLAGS:--rv}"
	;;
FreeBSD)
	echo TOOL=${TOOL:-clang} HOST=bsd
	;;
Darwin)
	echo HOST=bsd RANLIB_FLAGS="${RANLIB_FLAGS:--c}"
	;;
Minix)
	echo RANLIB="${RANLIB:-ar t}"
	;;
*BSD)
	echo HOST=bsd
	;;
Linux)
	echo TOOL=${TOOL:-gnu} HOST=linux
	;;
Plan9)
	echo TOOL=${TOOL:-plan9} HOST=plan9
	;;
esac


for i
do
	case $1 in
	-c)

		mach=`uname -m`

		case $mach in
		x86_64)
			mach=amd64
			;;
		aarch64)
			mach=arm64
			;;
		esac

		sys=`uname -s | tr 'A-Z' 'a-z'`
		echo CONF=$mach-$sys
		;;
	*)
		echo usage: config [-c] >&2
		exit 1
		;;
	esac
done
