#!/bin/sh

set -e

for i
do
	case "$i" in
	-p)
		proto=$2
		shift 2
		;;
	-*)
		echo usage: install [-p proto] root >&2
		exit 1
		;;
	esac
done

root=${1?'root missed'}

while read type perm name
do
	case $type in
	d)
		mkdir -p $root/$name
		;;
	f)
		cp $name $root/$name
		;;
	*)
		echo install: wrong entry type >&2
		exit 1
		;;
	esac

	chmod $perm $root/$name
done < ${proto:-scripts/proto.all}
