#!/bin/sh

set -e

touch deps.mk

cat <<EOF | ed -s deps.mk
1s/$//
g/^#deps/ s///
.;\$c
#deps
$(for i in `find . -name '*.c'`
do
	file=`basename $i | sed 's/\.c$/.o/'`
	dir=`dirname $i`

	sed -n "/^#include / {
		s///
		s@\"\(.*\)\"@$dir/$file: $dir/\1@p
		s@<\(scc/.*\)>@$dir/$file: \$(INCDIR)/scc/\1@p
	}" $i
done | LC_ALL=C sort -s)
.
g@^\./@ s///
g@ \./@ s// /
/^#deps/;$ g/^$/d
w
EOF
