#!/bin/sh

set -e

for i
do
	case "$i" in
	-p)
		proto=$2
		shift 2
		;;
	-*)
		echo usage: uninstall [-p proto] prefix >&2
		exit 1
		;;
	esac
done

prefix=${1?'prefix missed'}
proto=${proto:-scripts/proto.all}

while read type perm name
do
	case $type in
	d)
		echo $type $perm $name
		continue
		;;
	f)
		rm -f $prefix/$name
		;;
	*)
		echo install: wrong entry type >&2
		exit 1
		;;
	esac
done < $proto |
sort -r |
while read type perm name
do
	case $type in
	d)
		rmdir $prefix/$name || :
		;;
	esac
done
