#!/bin/sh

set -e

for i
do
	case "$i" in
	-p)
		proto=$2
		shift 2
		;;
	-*)
		echo 1=$1
		echo usage: uninstall [-p proto] prefix >&2
		exit 1
		;;
	esac
done

prefix=${1?'prefix missed'}

while read type perm name
do
	case $type in
	d)
		continue
		;;
	f)
		rm -f $prefix/$name
		;;
	*)
		echo install: wrong entry type >&2
		exit 1
		;;
	esac
done < ${proto:-scripts/proto}

while read type perm name
do
	case $type in
	d)
		rmdir $prefix/$name || :
		;;
	esac
done < ${proto:-scripts/proto}
