#deps
code.o: $(INCDIR)/bits/scc/scc.h
code.o: cc2.h
main.o: $(INCDIR)/bits/scc/arg.h
main.o: $(INCDIR)/bits/scc/scc.h
main.o: cc2.h
main.o: error.h
node.o: $(INCDIR)/bits/scc/scc.h
node.o: cc2.h
optm.o: $(INCDIR)/bits/scc/scc.h
optm.o: cc2.h
parser.o: $(INCDIR)/bits/scc/cstd.h
parser.o: $(INCDIR)/bits/scc/scc.h
parser.o: cc2.h
peep.o: $(INCDIR)/bits/scc/scc.h
peep.o: cc2.h
symbol.o: $(INCDIR)/bits/scc/scc.h
symbol.o: cc2.h
target/amd64-sysv/cgen.o: $(INCDIR)/bits/scc/scc.h
target/amd64-sysv/cgen.o: target/amd64-sysv/../../cc2.h
target/amd64-sysv/cgen.o: target/amd64-sysv/arch.h
target/amd64-sysv/code.o: $(INCDIR)/bits/scc/cstd.h
target/amd64-sysv/code.o: $(INCDIR)/bits/scc/scc.h
target/amd64-sysv/code.o: target/amd64-sysv/../../cc2.h
target/amd64-sysv/code.o: target/amd64-sysv/arch.h
target/amd64-sysv/optm.o: $(INCDIR)/bits/scc/scc.h
target/amd64-sysv/optm.o: target/amd64-sysv/../../cc2.h
target/amd64-sysv/types.o: $(INCDIR)/bits/scc/scc.h
target/amd64-sysv/types.o: target/amd64-sysv/../../cc2.h
target/arm64-sysv/types.o: $(INCDIR)/bits/scc/scc.h
target/arm64-sysv/types.o: target/arm64-sysv/../../cc2.h
target/i386-sysv/cgen.o: $(INCDIR)/bits/scc/scc.h
target/i386-sysv/cgen.o: target/i386-sysv/../../cc2.h
target/i386-sysv/cgen.o: target/i386-sysv/arch.h
target/i386-sysv/code.o: $(INCDIR)/bits/scc/cstd.h
target/i386-sysv/code.o: $(INCDIR)/bits/scc/scc.h
target/i386-sysv/code.o: target/i386-sysv/../../cc2.h
target/i386-sysv/code.o: target/i386-sysv/arch.h
target/i386-sysv/optm.o: $(INCDIR)/bits/scc/scc.h
target/i386-sysv/optm.o: target/i386-sysv/../../cc2.h
target/i386-sysv/types.o: $(INCDIR)/bits/scc/scc.h
target/i386-sysv/types.o: target/i386-sysv/../../cc2.h
target/qbe/cgen.o: $(INCDIR)/bits/scc/cstd.h
target/qbe/cgen.o: $(INCDIR)/bits/scc/scc.h
target/qbe/cgen.o: target/qbe/../../cc2.h
target/qbe/cgen.o: target/qbe/arch.h
target/qbe/code.o: $(INCDIR)/bits/scc/cstd.h
target/qbe/code.o: $(INCDIR)/bits/scc/scc.h
target/qbe/code.o: target/qbe/../../cc2.h
target/qbe/code.o: target/qbe/arch.h
target/qbe/optm.o: $(INCDIR)/bits/scc/scc.h
target/qbe/optm.o: target/qbe/../../cc2.h
target/z80-scc/cgen.o: $(INCDIR)/bits/scc/scc.h
target/z80-scc/cgen.o: target/z80-scc/../../cc2.h
target/z80-scc/cgen.o: target/z80-scc/arch.h
target/z80-scc/code.o: $(INCDIR)/bits/scc/cstd.h
target/z80-scc/code.o: $(INCDIR)/bits/scc/scc.h
target/z80-scc/code.o: target/z80-scc/../../cc2.h
target/z80-scc/code.o: target/z80-scc/arch.h
target/z80-scc/optm.o: $(INCDIR)/bits/scc/scc.h
target/z80-scc/optm.o: target/z80-scc/../../cc2.h
target/z80-scc/types.o: $(INCDIR)/bits/scc/scc.h
target/z80-scc/types.o: target/z80-scc/../../cc2.h
