.POSIX:
PROJECTDIR =../../..
include $(PROJECTDIR)/scripts/rules.mk
include ../rules.mk

OBJS = __getc.o\
       __putc.o\
       _flsbuf.o\
       _fpopen.o\
       clearerr.o\
       fclose.o\
       feof.o\
       ferror.o\
       fgetc.o\
       fgets.o\
       fopen.o\
       fprintf.o\
       fputc.o\
       fputs.o\
       fread.o\
       freopen.o\
       fseek.o\
       ftell.o\
       fwrite.o\
       getc.o\
       getchar.o\
       gets.o\
       perror.o\
       printf.o\
       putc.o\
       putchar.o\
       puts.o\
       rewind.o\
       setbuf.o\
       setvbuf.o\
       snprintf.o\
       sprintf.o\
       __iob.o\
       tmpnam.o\
       vfprintf.o\
       vsnprintf.o\
       vsprintf.o\
       vprintf.o\
       _allocbuf.o\

all: $(OBJS)
