.POSIX:
PROJECTDIR =../../..
include $(PROJECTDIR)/scripts/rules.mk
include ../rules.mk

OBJS =\
	__getc.$O\
	__putc.$O\
	_flsbuf.$O\
	_fpopen.$O\
	clearerr.$O\
	fclose.$O\
	feof.$O\
	ferror.$O\
	fflush.$O\
	fgetc.$O\
	fgets.$O\
	fopen.$O\
	fprintf.$O\
	fputc.$O\
	fputs.$O\
	fread.$O\
	freopen.$O\
	fseek.$O\
	ftell.$O\
	fwrite.$O\
	getc.$O\
	getchar.$O\
	gets.$O\
	perror.$O\
	printf.$O\
	putc.$O\
	putchar.$O\
	puts.$O\
	remove.$O\
	rename.$O\
	rewind.$O\
	setbuf.$O\
	setvbuf.$O\
	snprintf.$O\
	sprintf.$O\
	__iob.$O\
	tmpnam.$O\
	ungetc.$O\
	vfprintf.$O\
	vsnprintf.$O\
	vsprintf.$O\
	vprintf.$O\
	_allocbuf.$O\

all: $(OBJS)

include deps.mk
