.POSIX:
PROJECTDIR =../../..
include $(PROJECTDIR)/scripts/rules.mk
include ../rules.mk

OBJS = ctype.o\
       isalnum.o\
       isalpha.o\
       isascii.o\
       isblank.o\
       iscntrl.o\
       isdigit.o\
       isgraph.o\
       islower.o\
       isprint.o\
       ispunct.o\
       isspace.o\
       isupper.o\
       isxdigit.o\
       toascii.o\
       tolower.o\
       toupper.o\

all: $(OBJS)
